import type { Metadata } from 'next';
import { Nanum_Myeongjo } from 'next/font/google';

import * as Provider from './provider';
import './globals.css';

const nauumMyeongjo = Nanum_Myeongjo({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'weather',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nauumMyeongjo.className} w-full h-screen flex justify-center`}>
        <Provider.ReactQuery>
          <div className="w-full max-w-screen-sm h-full">{children}</div>
        </Provider.ReactQuery>
      </body>
    </html>
  );
}
